package Mapa;

import java.util.ArrayList;
import java.util.PriorityQueue;
import Dane.*;
import Menu.*;

public class Main {
    public static void main(String[] args) {
        Wezel polinka = new Wezel("polinka");
        Wezel C13_wyspianskiego = new Wezel("C13");
        Wezel C13_patio_portiernia = new Wezel("C13");
        Wezel C13_patio = new Wezel("C13");
        Wezel C8 = new Wezel("C8");
        Wezel C13_schodki = new Wezel("C13_schodki");
        Wezel wysp_norwida = new Wezel("wysp_norwida");
        Wezel A1_glowne = new Wezel("A1");
        Wezel A2 = new Wezel("A2");
        Wezel B1_wysp = new Wezel("B1");
        Wezel B1_smol = new Wezel("B1");
        Wezel B4 = new Wezel("B4");
        Wezel A3 = new Wezel("A3");
        Wezel A5 = new Wezel("A5");
        Wezel A1_brama = new Wezel("A1");
        Wezel A4 = new Wezel("A4");
        Wezel SKS = new Wezel("SKS");
        Wezel C2_norwida = new Wezel("C2_norwida");
        Wezel C6 = new Wezel("C6");
        Wezel pomnik_ogrod = new Wezel("pomnik_ogrod");
        Wezel C6_przejscie = new Wezel("C6_przejscie");
        Wezel C15 = new Wezel("C15");
        Wezel C3 = new Wezel("C3");
        Wezel C1 = new Wezel("C1");
        Wezel C2 = new Wezel("C2");
        Wezel C11 = new Wezel("C11");
        Wezel C16_jan = new Wezel("C16");
        Wezel C16_kampus = new Wezel("C16");
        Wezel D20 = new Wezel("D20");
        Wezel C5 = new Wezel("C5");
        Wezel pomnik_prof = new Wezel("pomnik_prof");
        Wezel D1_droga = new Wezel("D1_droga");
        Wezel D21_droga = new Wezel("D21_droga");
        Wezel D1 = new Wezel("D1");
        Wezel D21 = new Wezel("D21");
        Wezel D2 = new Wezel("D2");

        B1_wysp.dodaj_sasiada(A2, 40);
        B1_wysp.dodaj_sasiada(B1_smol, 90);
        B1_smol.dodaj_sasiada(B4, 30);
        B1_smol.dodaj_sasiada(A2, 100);
        B1_smol.dodaj_sasiada(A3, 50);
        A2.dodaj_sasiada(A3, 120);
        A2.dodaj_sasiada(A1_glowne, 130);
        A1_glowne.dodaj_sasiada(wysp_norwida, 50);
        wysp_norwida.dodaj_sasiada(C13_wyspianskiego, 130);
        C13_wyspianskiego.dodaj_sasiada(polinka, 70);
        C13_patio_portiernia.dodaj_sasiada(C13_wyspianskiego, 20);
        C13_patio_portiernia.dodaj_sasiada(C13_schodki, 80);
        C13_schodki.dodaj_sasiada(wysp_norwida, 80);
        wysp_norwida.dodaj_sasiada(A1_brama, 100);
        A3.dodaj_sasiada(A5, 180);
        A5.dodaj_sasiada(A1_brama, 70);
        A1_brama.dodaj_sasiada(C13_schodki, 100);
        C13_schodki.dodaj_sasiada(C6, 100);
        wysp_norwida.dodaj_sasiada(C6, 140);
        A1_brama.dodaj_sasiada(C6, 50);
        polinka.dodaj_sasiada(C8, 120);
        C8.dodaj_sasiada(C13_patio, 60);
        C13_patio.dodaj_sasiada(C13_patio_portiernia, 60);
        C13_patio.dodaj_sasiada(C6_przejscie, 70);
        C6_przejscie.dodaj_sasiada(pomnik_ogrod, 70);
        C6_przejscie.dodaj_sasiada(C15, 40);
        C15.dodaj_sasiada(pomnik_ogrod, 70);
        pomnik_ogrod.dodaj_sasiada(C6, 40);
        pomnik_ogrod.dodaj_sasiada(C2_norwida, 60);
        C6.dodaj_sasiada(C2_norwida, 80);
        A5.dodaj_sasiada(C2_norwida, 30);
        C8.dodaj_sasiada(C6_przejscie, 120);
        C6_przejscie.dodaj_sasiada(pomnik_prof, 80);
        C8.dodaj_sasiada(pomnik_prof, 100);
        C13_patio.dodaj_sasiada(pomnik_prof, 100);
        A5.dodaj_sasiada(C11, 100);
        A5.dodaj_sasiada(C1, 120);
        C1.dodaj_sasiada(C11, 60);
        C1.dodaj_sasiada(C16_jan, 100);
        C16_jan.dodaj_sasiada(C11, 120);
        C1.dodaj_sasiada(C2, 30);
        C1.dodaj_sasiada(C3, 30);
        C3.dodaj_sasiada(C2_norwida, 70);
        C3.dodaj_sasiada(pomnik_ogrod, 40);
        C1.dodaj_sasiada(C16_kampus, 90);
        C3.dodaj_sasiada(C16_kampus, 90);
        C16_jan.dodaj_sasiada(D20, 90);
        C16_jan.dodaj_sasiada(D1_droga, 60);
        C16_kampus.dodaj_sasiada(D1_droga, 60);
        C16_kampus.dodaj_sasiada(C5, 50);
        D1_droga.dodaj_sasiada(D20, 100);
        D1_droga.dodaj_sasiada(D1, 50);
        D1_droga.dodaj_sasiada(C5, 30);
        pomnik_prof.dodaj_sasiada(C5, 50);
        pomnik_prof.dodaj_sasiada(D21_droga, 80);
        D21_droga.dodaj_sasiada(SKS, 100);
        D21_droga.dodaj_sasiada(C5, 70);
        C5.dodaj_sasiada(D21, 80);
        D21_droga.dodaj_sasiada(D21, 40);
        D21.dodaj_sasiada(D1_droga, 60);
        D21.dodaj_sasiada(D1, 50);
        D21.dodaj_sasiada(D2, 20);
        D1.dodaj_sasiada(D2, 40);


        ArrayList<Wezel> wezly = new ArrayList<>();

        wezly.add(polinka);
        wezly.add(C13_wyspianskiego);
        wezly.add(C13_patio);
        wezly.add(C13_schodki);
        wezly.add(C13_patio_portiernia);
        wezly.add(C8);
        wezly.add(wysp_norwida);
        wezly.add(A1_glowne);
        wezly.add(A2);
        wezly.add(B1_wysp);
        wezly.add(B1_smol);
        wezly.add(B4);
        wezly.add(A3);
        wezly.add(A5);
        wezly.add(A1_brama);
        wezly.add(A4);
        wezly.add(SKS);
        wezly.add(C2_norwida);
        wezly.add(C6);
        wezly.add(pomnik_ogrod);
        wezly.add(C6_przejscie);
        wezly.add(C15);
        wezly.add(C3);
        wezly.add(C1);
        wezly.add(C2);
        wezly.add(C11);
        wezly.add(C16_jan);
        wezly.add(C16_kampus);
        wezly.add(D20);
        wezly.add(C5);
        wezly.add(pomnik_prof);
        wezly.add(D1_droga);
        wezly.add(D21_droga);
        wezly.add(D1);
        wezly.add(D21);
        wezly.add(D2);


        Menu menu = Dane.stworzMenu();
        System.out.println(menu.jakieDanie());
//        Dijkstra dijkstra = new Dijkstra(wezly, D1, B4);
//        dijkstra.dijkstra_algo();
//        dijkstra.getDroga();
    }
}